CREATE TABLE IF NOT EXISTS `ESTACAO_001`(
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`TEMPERATURA` double NOT NULL,
	`UMIDADE` double NOT NULL,
	`LUMINOSIDADE` double NOT NULL,
	PRIMARY KEY (`ID`)
) DEFAULT CHARSET = utf8;